apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-secret
{{ include "boldbi.namespace" . | indent 2 }}
type: Opaque
stringData:
  widget_bing_map_enable_secret: "{{ .Values.bingMapWidget.enabled }}"
  widget_bing_map_api_key_secret: "{{ .Values.bingMapWidget.apiKey }}"
  application_insights_connection_string_secret: "{{ .Values.azureApplicationInsights.connectionString }}"