apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  {{- if .Values.bingMapWidget.bingMapSecretName }}
  name: {{ .Values.bingMapWidget.bingMapSecretName }}
  {{- else }}
  name: bold-secret
  {{- end }}
{{ include "boldbi.namespace" . | indent 2 }}
type: Opaque
stringData:
  widget_bing_map_enable_secret: "{{ $.Values.bingMapWidget.enabled }}"
  widget_bing_map_api_key_secret: "{{ $.Values.bingMapWidget.apiKey }}"