apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: version-config

data:
  BOLD_SERVICES_ID_WEB_VERSION: bold-identity:"{{ $.Values.image.idTag }}"
  BOLD_SERVICES_ID_API_VERSION: bold-identity-api:"{{ $.Values.image.idTag }}"
  BOLD_SERVICES_UMS_WEB_VERSION: bold-ums:"{{ $.Values.image.idTag }}"
  BOLD_SERVICES_BI_WEB_VERSION: boldbi-server:"{{ $.Values.image.biTag }}"
  BOLD_SERVICES_BI_API_VERSION: boldbi-server-api:"{{ $.Values.image.biTag }}"
  BOLD_SERVICES_BI_JOBS_VERSION: boldbi-server-jobs:"{{ $.Values.image.biTag }}"
  BOLD_SERVICES_BI_DESIGNER_VERSION: boldbi-designer:"{{ $.Values.image.biTag }}"
  BOLD_SERVICES_REPORTING_WEB_VERSION: boldreports-server:"{{ $.Values.image.reportsTag }}"
  BOLD_SERVICES_REPORTING_API_VERSION: boldreports-server-api:"{{ $.Values.image.reportsTag }}"
  BOLD_SERVICES_REPORTING_SERVICE_VERSION: boldreports-designer:"{{ $.Values.image.reportsTag }}"
  BOLD_SERVICES_REPORTING_JOBS_VERSION: boldreports-server-jobs:"{{ $.Values.image.reportsTag }}"
  