{{- if eq .Values.loadBalancer.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  {{- if .Values.istioConfig.virtualServiceName }}
  name: {{ .Values.istioConfig.virtualServiceName }}
  {{- else }}
  name: bold-virtual-service
  {{- end }}
{{ include "boldbi.namespace" . | indent 2 }}
spec:
  {{- if .Values.loadBalancer.multipleHost }}
  hosts:
  {{- range $host := ( index .Values.loadBalancer.multipleHost.hostArray 0 ).hosts }}
  - {{ $host }}
  {{- end }}
  {{- else }}
  hosts:
  - {{ (split "/" .Values.appBaseUrl)._2 }}
  {{- end }}
  gateways:
  {{- if .Values.istioConfig.gatewayName }}
  - {{ .Values.istioConfig.gatewayName }}
  {{- else }}
  - bold-gateway
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /reporting/reportservice
    route:
    - destination:
        port:
          number: 6553
        host: reports-reportservice-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting/api
    route:
    - destination:
        port:
          number: 6551
        host: reports-api-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting/jobs
    route:
    - destination:
        port:
          number: 6552
        host: reports-jobs-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /bi/api
    route:
    - destination:
        port:
          number: 6005
        host: bi-api-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /bi/jobs
    route:
    - destination:
        port:
          number: 6006
        host: bi-jobs-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /bi/designer
    route:
    - destination:
        port:
          number: 6007
        host: bi-dataservice-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /reporting
    route:
    - destination:
        port:
          number: 6550
        host: reports-web-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /bi
    route:
    - destination:
        port:
          number: 6004
        host: bi-web-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        port:
          number: 6001
        host: id-api-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /ums
    route:
    - destination:
        port:
          number: 6002
        host: id-ums-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 6000
        host: id-web-service
    retries:
      attempts: 3
      retryOn: gateway-error,connect-failure,refused-stream
{{- end }}